// Exact fma emulation, for the tests: the golden data of Brent and of fma itself were
// generated by Julia code in which `muladd` was fused (dynamically dispatched
// `evalpoly`), so reproducing them bit for bit needs fma semantics. The solver itself
// uses plain multiply-add (src/solver/math.ts, `evalpoly`).

import { exactRational, ratToDouble } from "../src/solver/exact.ts";

const SPLITTER = 134217729;            // 2^27 + 1 (Veltkamp)
const f64 = new Float64Array(1);
const u64 = new BigUint64Array(f64.buffer);

function twoSum(a: number, b: number): [number, number] {
  const s = a + b;
  const bb = s - a;
  return [s, (a - (s - bb)) + (b - bb)];
}

function twoProd(a: number, b: number): [number, number] {
  const p = a * b;
  let t = SPLITTER * a;
  const ah = t - (t - a), al = a - ah;
  t = SPLITTER * b;
  const bh = t - (t - b), bl = b - bh;
  return [p, ((ah * bh - p) + ah * bl + al * bh) + al * bl];
}

/** Round-to-odd of a + b (the exact sum is s + e). */
function addOdd(a: number, b: number): number {
  const [s, e] = twoSum(a, b);
  if (e === 0 || s === 0) return s;
  f64[0] = s;
  if ((u64[0]! & 1n) === 1n) return s;            // already odd
  // move one ulp towards the exact value: the neighbour with odd last bit
  u64[0] = (s > 0) === (e > 0) ? u64[0]! + 1n : u64[0]! - 1n;
  return f64[0]!;
}

/**
 * Correctly rounded a·b + c, as Julia's `fma` (and `muladd`, which Julia compiles to a
 * hardware FMA on x86-64 with FMA3 and on ARM64). JavaScript has no fma, so it is
 * emulated: Boldo & Melquiond, "Emulation of FMA and correctly rounded sums: proved
 * algorithms using rounding to odd", IEEE Trans. Comput. 57 (2008), with an exact
 * BigInt evaluation where the error-free transformations could under- or overflow.
 */
export function fma(a: number, b: number, c: number): number {
  const p = a * b;
  if (!Number.isFinite(a) || !Number.isFinite(b)) return p + c;   // Inf/NaN as in IEEE fma
  if (!Number.isFinite(c)) return c;                               // exact a·b is finite
  if (a === 0 || b === 0) return p + c;           // exact product: one rounding, signed zeros as fma
  const ap = Math.abs(p), aa = Math.abs(a), ab = Math.abs(b), ac = Math.abs(c);
  const SAFE_LO = 2 ** -900, SAFE_HI = 2 ** 900;
  if (ap < SAFE_LO || ap > SAFE_HI || aa > SAFE_HI || ab > SAFE_HI || aa < SAFE_LO || ab < SAFE_LO ||
      (ac !== 0 && (ac < SAFE_LO || ac > SAFE_HI))) {
    return fmaExact(a, b, c);
  }
  const [uh, ul] = twoProd(a, b);
  const [th, tl] = twoSum(c, uh);
  const v = addOdd(tl, ul);
  const r = th + v;
  // exact cancellation to zero: IEEE gives +0 in round-to-nearest
  return r === 0 ? 0 : r;
}

function fmaExact(a: number, b: number, c: number): number {
  const [an, ad] = exactRational(a);
  const [bn, bd] = exactRational(b);
  const [cn, cd] = exactRational(c);
  // a·b + c = (an·bn·cd + cn·ad·bd) / (ad·bd·cd)
  const num = an * bn * cd + cn * ad * bd;
  if (num === 0n) return 0;
  return ratToDouble(num, ad * bd * cd);
}

/** Horner with fma, as Julia's `evalpoly` when its `muladd`s are fused. */
export function evalpolyFma(x: number, c: readonly number[]): number {
  let n = c.length - 1;
  let s = c[n] ?? 0;
  while (n > 0) {
    n--;
    s = fma(x, s, c[n] ?? 0);
  }
  return s;
}

