// Loader for the golden data generated by reference/generate_golden.jl (plan §5.1).
// Files are gzipped JSON; non-finite numbers are stored as the strings "Inf", "-Inf",
// "NaN" (plan §4.7) and decoded here.

import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";

export interface GoldenMeta {
  commit: string;
  version: string;
  julia: string;
  packages: Record<string, string>;
  generated: string;
}

const NONFINITE: Record<string, number> = { Inf: Infinity, "-Inf": -Infinity, NaN: NaN };

export function decodeNonfinite(_key: string, value: unknown): unknown {
  return typeof value === "string" && value in NONFINITE ? NONFINITE[value] : value;
}

export const GOLDEN_DIR = new URL("./golden/", import.meta.url);

export const GOLDEN_FILES = [
  "basics", "format", "kernels", "fans_dense", "residual", "solve_examples", "solve_random",
  "solve_stress", "solve_small_bt", "solve_perp", "output", "brent",
] as const;
export type GoldenName = (typeof GOLDEN_FILES)[number];

const cache = new Map<string, unknown>();

/** Parsed golden file `test/golden/<name>.json.gz`. */
export function loadGolden<T = Record<string, unknown>>(name: GoldenName): T & { meta: GoldenMeta } {
  let v = cache.get(name);
  if (v === undefined) {
    const text = gunzipSync(readFileSync(new URL(`${name}.json.gz`, GOLDEN_DIR))).toString("utf8");
    v = JSON.parse(text, decodeNonfinite);
    cache.set(name, v);
  }
  return v as T & { meta: GoldenMeta };
}

/** Text of a golden file that is stored as is (CSV files, test data of the Julia package). */
export function goldenText(path: string): string {
  return readFileSync(new URL(path, GOLDEN_DIR), "utf8");
}
