# Writes src/solver/rk/vern9.ts from the Float64 coefficients that OrdinaryDiffEqVerner
# (pinned in reference/Manifest.toml) actually uses: the 16-stage Vern9 tableau, the
# 10 extra stages of its lazy dense output and the interpolation polynomials (plan §4.1).
# Run: julia --project=reference reference/gen_vern9.jl
using ExactMHDRiemannSolver
const V = ExactMHDRiemannSolver.OrdinaryDiffEqVerner

tab = V.Vern9Tableau(Float64, Float64)
ext = V.Vern9ExtraStages(Float64, Float64)
itp = V.Vern9InterpolationCoefficients(Float64)
g(o, s) = getfield(o, Symbol(s))

ns = 26
c = zeros(ns)
A = [Tuple{Int,Float64}[] for _ in 1:ns]
for i in 2:14
    c[i] = g(tab, "c$(i-1)")
end
c[15] = c[16] = 1.0
for o in (tab, ext), f in fieldnames(typeof(o))
    s = String(f)
    m = match(r"^a(\d\d)(\d\d)$", s)
    m === nothing || push!(A[parse(Int, m[1])], (parse(Int, m[2]), getfield(o, f)))
    # the extra stages name their nodes by stage (c17…c26); the main tableau's c1…c13
    # belong to stages 2…14 (set above)
    m = match(r"^c(\d\d)$", s)
    o === ext && m !== nothing && (c[parse(Int, m[1])] = getfield(o, f))
end
b = Tuple{Int,Float64}[]; bt = Tuple{Int,Float64}[]
for f in fieldnames(typeof(tab))
    s = String(f)
    (m = match(r"^b(\d+)$", s)) === nothing || push!(b, (parse(Int, m[1]), getfield(tab, f)))
    (m = match(r"^btilde(\d+)$", s)) === nothing || push!(bt, (parse(Int, m[1]), getfield(tab, f)))
end
# interpolation: b1Θ = Θ·poly(r011..r019); bjΘ = Θ²·poly(rj2..rj9)
interp = Tuple{Int,Int,Vector{Float64}}[]
for j in (1, 8:15..., 17:26...)
    lo = j == 1 ? 1 : 2
    push!(interp, (j, lo, [g(itp, "r" * lpad(j, 2, '0') * string(p)) for p in lo:9]))
end
# sanity: consistency of the tableau
# (row sums equal c up to the rounding of the large coefficients of the higher stages)
for i in 2:ns
    amax = maximum(x -> abs(last(x)), A[i])
    @assert abs(sum(last, A[i]) - c[i]) <= 64 * eps() * amax "row sum $i"
end
@assert isapprox(sum(last, b), 1.0; atol = 1e-14)

r(x) = repr(x)
pairs_ts(v) = "[" * join(["[$(j - 1), $(r(x))]" for (j, x) in v], ", ") * "]"
open(joinpath(@__DIR__, "..", "src", "solver", "rk", "vern9.ts"), "w") do io
    println(io, "// GENERATED by reference/gen_vern9.jl from OrdinaryDiffEqVerner ",
        pkgversion(V), " (Vern9Tableau, Vern9ExtraStages,")
    println(io, "// Vern9InterpolationCoefficients for Float64). Do not edit. Stage indices are 0-based:")
    println(io, "// stage i here is k(i+1) in OrdinaryDiffEqVerner. Stages 0-15 form a step, 16-25 are the")
    println(io, "// extra stages of the dense output.\n")
    println(io, "import type { Tableau } from \"./engine.ts\";\n")
    println(io, "export const VERN9: Tableau = {")
    println(io, "  name: \"Vern9\",")
    println(io, "  order: 9,")
    println(io, "  stages: 16,")
    println(io, "  c: [", join(r.(c), ", "), "],")
    println(io, "  a: [")
    for i in 1:ns
        println(io, "    ", pairs_ts(A[i]), ",")
    end
    println(io, "  ],")
    println(io, "  b: ", pairs_ts(b), ",")
    println(io, "  btilde: ", pairs_ts(bt), ",")
    println(io, "  interp: [")
    for (j, lo, cs) in interp
        println(io, "    { stage: $(j - 1), pow: $lo, coeffs: [", join(r.(cs), ", "), "] },")
    end
    println(io, "  ],")
    println(io, "};")
end
println("wrote src/solver/rk/vern9.ts")
